global_variables:
  release: "2023-07-26-alpha.0"
  s3_region: "us-west-2"
  default_theme: "places"
  default_type: "*"
  filter_by_bbox: true
  filter_by_country: false
  bbox_file_path: "examples/bbox.geojson"
  country_iso_code: "EG"
  output_file_path: "examples/output.parquet"
  default_epsg: 4326

s3_credentials: # Optional
  access_key: "YOUR_ACCESS_KEY"
  secret_key: "YOUR_SECRET_KEY"
  session_token: "YOUR_SESSION_TOKEN"

urls:
  Amazon_S3: "s3://overturemaps-us-west-2/release/{release}/theme={theme}/type={ptype}/*"
  Microsoft_Azure: "https://overturemapswestus2.blob.core.windows.net/release/{release}/theme={theme}/type={ptype}/*"
  Wherobots_S3: "s3://wherobots-public-data/overturemaps-us-west-2/release/{release}/theme={theme}/type={ptype}"

themes:
  - name: "admins"
    ptypes:
      - "locality"
      - "administrativeBoundary"
  - name: "buildings"
    ptypes:
      - "building"
  - name: "places"
    ptypes:
      - "place"
  - name: "transportation"
    ptypes:
      - "connector"
      - "segment"
