[tool.poetry]
name = "overturemapsdownloader"
version = "0.1.4"
description = "Overture Maps Downloader simplifies geospatial data manipulation"
authors = ["Youssef-Harby <me@youssefharby.com>"]
readme = "README.md"
include = ["config.yml"]

[tool.poetry.scripts]
OMDownloader = "overturemapsdownloader.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.9.0"}
jupyter = "^1.0.0"
dask-geopandas = "^0.3.1"
pyarrow = "^13.0.0"
adlfs = "^2023.8.0"
duckdb = "0.8.2.dev4142"
geopandas = "^0.13.2"
shapely = "^2.0.1"
gdal = {version = "^3.7.2", optional = true}
fiona = "^1.9.4.post1"
fastparquet = "^2023.8.0"
s3fs = "^2023.9.0"
dask = {extras = ["complete"], version = "^2023.9.1"}

[tool.poetry.extras]
gdal_support = ["gdal"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
in-project = true